<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class BagianSeeder extends Seeder
{
    public function run()
    {
        $data = [
            //OPERATOR
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK1', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK1', 'area' => 'KK1A', 'keterangan' => ''],
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK1', 'area' => 'KK1B', 'keterangan' => ''],
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK2', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK2', 'area' => 'KK2A', 'keterangan' => ''],
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK2', 'area' => 'KK2B', 'keterangan' => ''],
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK2', 'area' => 'KK2C', 'keterangan' => ''],
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK5', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK5', 'area' => 'KK5', 'keterangan' => ''],
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK7', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK7', 'area' => 'KK7K', 'keterangan' => ''],
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK7', 'area' => 'KK7L', 'keterangan' => ''],
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK8', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK8', 'area' => 'KK8D', 'keterangan' => ''],
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK8', 'area' => 'KK8F', 'keterangan' => ''],
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK8', 'area' => 'KK8J', 'keterangan' => ''],
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK9', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK9', 'area' => 'KK9', 'keterangan' => ''],
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK10', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK10', 'area' => 'KK10', 'keterangan' => ''],
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK11', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'OPERATOR', 'area_utama' => 'KK11', 'area' => 'KK11', 'keterangan' => ''],
            //knitter
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK1', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK1', 'area' => 'KK1A', 'keterangan' => ''],
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK1', 'area' => 'KK1B', 'keterangan' => ''],
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK2', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK2', 'area' => 'KK2A', 'keterangan' => ''],
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK2', 'area' => 'KK2B', 'keterangan' => ''],
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK2', 'area' => 'KK2C', 'keterangan' => ''],
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK5', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK5', 'area' => 'KK5', 'keterangan' => ''],
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK7', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK7', 'area' => 'KK7K', 'keterangan' => ''],
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK7', 'area' => 'KK7L', 'keterangan' => ''],
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK8', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK8', 'area' => 'KK8D', 'keterangan' => ''],
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK8', 'area' => 'KK8F', 'keterangan' => ''],
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK8', 'area' => 'KK8J', 'keterangan' => ''],
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK9', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK9', 'area' => 'KK9', 'keterangan' => ''],
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK10', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK10', 'area' => 'KK10', 'keterangan' => ''],
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK11', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'KNITTER', 'area_utama' => 'KK11', 'area' => 'KK11', 'keterangan' => ''],
            // MONTIR
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK1', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK1', 'area' => 'KK1A', 'keterangan' => ''],
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK1', 'area' => 'KK1B', 'keterangan' => ''],
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK2', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK2', 'area' => 'KK2A', 'keterangan' => ''],
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK2', 'area' => 'KK2B', 'keterangan' => ''],
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK2', 'area' => 'KK2C', 'keterangan' => ''],
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK5', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK5', 'area' => 'KK5', 'keterangan' => ''],
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK7', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK7', 'area' => 'KK7K', 'keterangan' => ''],
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK7', 'area' => 'KK7L', 'keterangan' => ''],
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK8', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK8', 'area' => 'KK8D', 'keterangan' => ''],
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK8', 'area' => 'KK8F', 'keterangan' => ''],
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK8', 'area' => 'KK8J', 'keterangan' => ''],
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK9', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK9', 'area' => 'KK9', 'keterangan' => ''],
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK10', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK10', 'area' => 'KK10', 'keterangan' => ''],
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK11', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'MONTIR', 'area_utama' => 'KK11', 'area' => 'KK11', 'keterangan' => ''],
            // ROSSO
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK1', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK1', 'area' => 'KK1A', 'keterangan' => ''],
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK1', 'area' => 'KK1B', 'keterangan' => ''],
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK2', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK2', 'area' => 'KK2A', 'keterangan' => ''],
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK2', 'area' => 'KK2B', 'keterangan' => ''],
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK2', 'area' => 'KK2C', 'keterangan' => ''],
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK5', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK5', 'area' => 'KK5', 'keterangan' => ''],
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK7', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK7', 'area' => 'KK7K', 'keterangan' => ''],
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK7', 'area' => 'KK7L', 'keterangan' => ''],
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK8', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK8', 'area' => 'KK8D', 'keterangan' => ''],
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK8', 'area' => 'KK8F', 'keterangan' => ''],
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK8', 'area' => 'KK8J', 'keterangan' => ''],
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK9', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK9', 'area' => 'KK9', 'keterangan' => ''],
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK10', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK10', 'area' => 'KK10', 'keterangan' => ''],
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK11', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'ROSSO', 'area_utama' => 'KK11', 'area' => 'KK11', 'keterangan' => ''],
            // JAHIT
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK1', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK1', 'area' => 'KK1A', 'keterangan' => ''],
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK1', 'area' => 'KK1B', 'keterangan' => ''],
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK2', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK2', 'area' => 'KK2A', 'keterangan' => ''],
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK2', 'area' => 'KK2B', 'keterangan' => ''],
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK2', 'area' => 'KK2C', 'keterangan' => ''],
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK5', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK5', 'area' => 'KK5', 'keterangan' => ''],
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK7', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK7', 'area' => 'KK7K', 'keterangan' => ''],
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK7', 'area' => 'KK7L', 'keterangan' => ''],
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK8', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK8', 'area' => 'KK8D', 'keterangan' => ''],
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK8', 'area' => 'KK8F', 'keterangan' => ''],
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK8', 'area' => 'KK8J', 'keterangan' => ''],
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK9', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK9', 'area' => 'KK9', 'keterangan' => ''],
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK10', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK10', 'area' => 'KK10', 'keterangan' => ''],
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK11', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'JAHIT', 'area_utama' => 'KK11', 'area' => 'KK11', 'keterangan' => ''],
            // OBRAS
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK1', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK1', 'area' => 'KK1A', 'keterangan' => ''],
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK1', 'area' => 'KK1B', 'keterangan' => ''],
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK2', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK2', 'area' => 'KK2A', 'keterangan' => ''],
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK2', 'area' => 'KK2B', 'keterangan' => ''],
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK2', 'area' => 'KK2C', 'keterangan' => ''],
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK5', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK5', 'area' => 'KK5', 'keterangan' => ''],
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK7', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK7', 'area' => 'KK7K', 'keterangan' => ''],
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK7', 'area' => 'KK7L', 'keterangan' => ''],
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK8', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK8', 'area' => 'KK8D', 'keterangan' => ''],
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK8', 'area' => 'KK8F', 'keterangan' => ''],
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK8', 'area' => 'KK8J', 'keterangan' => ''],
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK9', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK9', 'area' => 'KK9', 'keterangan' => ''],
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK10', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK10', 'area' => 'KK10', 'keterangan' => ''],
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK11', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'OBRAS', 'area_utama' => 'KK11', 'area' => 'KK11', 'keterangan' => ''],
            // SEWING
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK1', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK1', 'area' => 'KK1A', 'keterangan' => ''],
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK1', 'area' => 'KK1B', 'keterangan' => ''],
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK2', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK2', 'area' => 'KK2A', 'keterangan' => ''],
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK2', 'area' => 'KK2B', 'keterangan' => ''],
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK2', 'area' => 'KK2C', 'keterangan' => ''],
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK5', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK5', 'area' => 'KK5', 'keterangan' => ''],
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK7', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK7', 'area' => 'KK7K', 'keterangan' => ''],
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK7', 'area' => 'KK7L', 'keterangan' => ''],
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK8', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK8', 'area' => 'KK8D', 'keterangan' => ''],
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK8', 'area' => 'KK8F', 'keterangan' => ''],
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK8', 'area' => 'KK8J', 'keterangan' => ''],
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK9', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK9', 'area' => 'KK9', 'keterangan' => ''],
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK10', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK10', 'area' => 'KK10', 'keterangan' => ''],
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK11', 'area' => NULL, 'keterangan' => ''],
            ['nama_bagian' => 'SEWING', 'area_utama' => 'KK11', 'area' => 'KK11', 'keterangan' => ''],
            // data kosong
            ['nama_bagian' => '-', 'area_utama' => '-', 'area' => NULL, 'keterangan' => ''],
        ];

        $this->db->table('bagian')->insertBatch($data);
    }
}
